image: alpine:latest

deploy:wishalloy:
  stage: deploy
  before_script:
    # Override the global before_script:
    - apk update
    - apk add openssh
    - apk add rsync
    - cd wishalloy
  script:
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    # We're using tr to fix line endings which makes ed25519 keys work
    # without extra base64 encoding.
    #
    #     https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    #
    - echo "$WISHALLOY_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan wishalloy.io  > ~/.ssh/known_hosts
    # TODO: Sane permissions on rsync-ed files (www-data:www-data). This
    #       should be handled server-side, but I'm leaving this note here
    #       for bookkeeping purposes.
    - rsync -av --delete ./ deploybot-skaiser@wishalloy.io:/srv/skaiser/
